### ISSUE TITLE
Looking forward for more info on this project.

### ISSUE THREAD

**Issue by arunshekher** [lonalore/simpletest#1]
Is it this project in working order if yes how is it implemented and used? I'm assuming that it is meant for PHPUnit testing with e107? 

I'm looking forward for a way to unit test e107 themes and plugin I'm developing for personal use and for the community.

**Comment by lonalore** [comment]
This project is not finished yet. My plan was to make a plugin for providing an e107-specific testing API, which is modeled after the [SimpleTest PHP library](http://simpletest.sourceforge.net/). But I have not been able to finish it mainly because of lack of time. But some missing key features also played a part. For example, I would have needed something for batch operations to run tests without interruption, and this led me to create [Batch API](https://github.com/lonalore/batch) plugin. So in essence, this project is not finished yet, but I really want to get it finished and I really want to continue working on it, as soon as it is possible, because there is a great need for something solution to write and run test cases for e107 core, plugins and themes.

**Comment by arunshekher** [comment]
Yes, of-course test driven development follows the line of 'scientific-method' and I prefer that over manual testing and hope that be the way forward for e107 dev. 

I feel I'm not skillfully or knowledge-wise competent to help you with actual code but I support this concept and can probably help with testing and giving feedback. I'm looking forward for this getting materialized. Thank you for your time and effort.

**Comment by lonalore** [comment]
I think a ready-to-use version is coming soon. ;-)

![peek 2017-12-19 14-01](https://user-images.githubusercontent.com/6043821/34159713-7315a034-e4ca-11e7-904e-6ea8dc21161d.gif)

**Comment by lonalore** [comment]
One release blocking issue left:
- Finding a way to override constants in e107. ([runkit](http://php.net/manual/en/book.runkit.php)) - This is essential for that the files (cache and other files generated during tests) will be stored in a completely separated folder. But e107 uses constants for **e107_system** and **e107_media** paths.

**Comment by lonalore** [comment]
The plugin works properly now with runkit.

**Comment by arunshekher** [comment]
@lonalore Thank you for the updates. Was out n away awhile. Will tryout soon.
